name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest pytest-cov flake8==7.0.0 black==24.3.0 isort==5.13.2
      - name: Lint (flake8)
        run: flake8 .
      - name: Format check (black)
        run: black --check .
      - name: Import order (isort)
        run: isort --profile black --check-only .
      - name: Run tests
        run: pytest --cov=src/deepseek_wrapper --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false